name: flutter_network
description: This plugin provides networking capabilities for your Flutter application. It includes functionality for making various types of HTTP requests and handling API responses.
version: 1.0.0+2
homepage: https://github.com/BrainStation-23/Flutter-Toolkit/tree/main/network
repository: https://github.com/BrainStation-23/Flutter-Toolkit/tree/main/network

environment:
  sdk: '>=2.18.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  # Network and Connectivity
  dio: ^5.3.3
  # Logging
  pretty_dio_logger: ^1.3.1
  logger: ^2.0.2+1
  # Utils
  internet_connection_checker: ^1.0.0+1
  equatable: ^2.0.5

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  module:
    androidX: true
    androidPackage: com.brainstation23.network
    iosBundleIdentifier: com.brainstation23.network
